[project]
name = "video-converter"
version = "0.2.4"
description = "Video converter: NVENC+AAC"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyinstaller>=6.16.0",
    "wxpython>=4.2.4",
]
