[project]
name = "video-converter"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyinstaller>=6.16.0",
    "wxpython>=4.2.4",
]
